name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    name: Run Semgrep OSS
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Check out repository
        # actions/checkout@v4.1.7
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Run Semgrep Scan
        run: semgrep scan --config auto .
