name: Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions: {}

jobs:
  trivy:
    name: Run Trivy Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      # actions/checkout@v4.2.2
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Build Docker image
        run: |
          docker build --no-cache -t my-app:${{ github.sha }} .

      - name: Generate Trivy Image SARIF Report
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@416ff0dea110f80f0f56f0046500dbf7420e4bb0
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-image-scan'

      - name: Scan Docker Image with Trivy (Table & Fail check)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
